
* Dynotune - Hub for performance measurement

Work in progress.

** Purpose

*Data structure availability in common lisp is low* : Due to the scarsity of reliable, fast container library,
Common Lisp suffers from its inclination to list structure. While the so-called "library problem" is largely
resolved by quicklisp, I believe the data structure availability in common lisp is low, rather than “too
high” as in application tools such as web server, databases, GUI.

*Data structure is all about performance.* : Extensibility is not the core value. Users do not care how the
library is implemented. This framework measures the actual time and space complexity.

*This is a hub, rather than a library.* : This framework is going to evaluate each library performance in the
same computing environment. It defines a set of benchmark suite (data), and the interfaces to libraries are
submitted by the user. Competition!

** Design Sketch

The design of the whole framework will be similar to [[http://benchmarksgame.alioth.debian.org/][Computer Language Benchmarks Game]].  It measures the
end-to-end performance. This is important in order to evaluate the performance across various Common
Lisp implementations.

It also accepts submissions in other languages, such as C or C++. API is defined in shell-script basis.

** Notes

*Flexibility but not extensibility.* : Flexibility is different from extensibility. An instance of flexibility
is the customizable sorting function in merge sort.


** Dependencies

This library is at least tested on implementation listed below:

+ SBCL 1.3.7 on X86-64 Linux  4.4.0-31-generic (author's environment)

Also, it depends on the following libraries:

+ iterate by  ::
    Jonathan Amsterdam's iterator/gatherer/accumulator facility

+ alexandria by  ::
    Alexandria is a collection of portable public domain utilities.



** Installation


** Author

+ Masataro Asai (guicho2.71828@gmail.com)

* Copyright

Copyright (c) 2016 Masataro Asai (guicho2.71828@gmail.com)


* License

Licensed under the LLGPL License.



