
* Dynotune - Hub for library evaluation

+Idea level.+ +Work in progress.+ +alpha+ +beta+ *Abandoned*.

I want to reuse the same library name for a different purpose, so this project is abandoned.

** Purpose

*Data structure availability in common lisp is still low* although the so-called "library problem" is largely
resolved by quicklisp. One reason is that there is no standardized way to evaluate a library: One can claim it
to be fast, but it is not easy to verify it in most cases.

*Performance, Scalability, Quality.* :
Performance includes low-level optimization.
Scalability is not necessarily the synonym of performance, since there is a tradeoff.
Quality represents the quality of API, documentation, design and cleanness of the implementation of the library.
(These are highly subjective, but still worth an evaluation.)

*Hub, rather than a library?* : This framework is going to evaluate each library performance in the same
computing environment. It defines a set of benchmark suite (data), and the interfaces to libraries are
submitted by the user. Competition!

# ** Notes
# 
# *Flexibility but not extensibility.* : 
# 
# Extensibility is not the core value. Users do not care how the
# library is implemented. This framework measures the actual time and space complexity.
# 
# 
# In this documentation Flexibility is different from extensibility. An instance of flexibility
# is the customizable sorting function in merge sort. An instance of extensibility is extending Binary tree
# implementation to Red-black-tree using CLOS.

** Design Sketch

API is defined in shell-script basis.
Input is through a file, output is through the standard output.

It also accepts submissions in other languages, such as C or C++.

Submission is done by a pull-request.
For implementions based on lisp, they should be written in [[https://github.com/roswell/roswell][roswell]] scripts.
For other languages, each implementation should include a simple makefile and a source code.

** Dependencies

This library is at least tested on implementation listed below:

+ SBCL 1.3.7 on X86-64 Linux  4.4.0-31-generic (author's environment)

Also, it depends on the following libraries:

+ iterate by  ::
    Jonathan Amsterdam's iterator/gatherer/accumulator facility

+ alexandria by  ::
    Alexandria is a collection of portable public domain utilities.



** Installation


** Author

+ Masataro Asai (guicho2.71828@gmail.com)

* Copyright

Copyright (c) 2016 Masataro Asai (guicho2.71828@gmail.com)


* License

Licensed under the LLGPL License.



